# ZH overrides: required glossary (rule 6) + recurring nav/footer/button boilerplate.
# These WIN over machine/segment translations.

OVERRIDES = {
    # --- Required product terminology (rule 6) ---
    "SPC Flooring": "SPC地板",
    "SPC flooring": "SPC地板",
    "WPC Wall Panel": "WPC墙板",
    "WPC Wall Panels": "WPC墙板",
    "WPC Wall Panel System": "WPC墙板系统",
    "PVC Wall Panel": "PVC墙板",
    "PVC Wall Panels": "PVC墙板",
    "Carbon Crystal Panel": "碳晶板",
    "Carbon Crystal Panels": "碳晶板",
    "Carbon Crystal": "碳晶板",
    "Acoustic Panel": "吸音板",
    "Acoustic Panels": "吸音板",
    "Acoustic Wall Panel": "吸音墙板",
    "HPL Compact Laminate": "HPL防火板",
    "HPL Compact Laminates": "HPL防火板",
    "Bamboo Crystal Panel": "竹晶板",
    "Bamboo Crystal Panels": "竹晶板",
    "Bamboo Crystal": "竹晶板",
    "Aluminium Composite Panel": "铝复合板",
    "Aluminium Composite Panels": "铝复合板",
    "Aluminium Honeycomb Panel": "铝蜂窝板",
    "Aluminium Honeycomb Panels": "铝蜂窝板",
    "Flexible Stone Veneer": "柔性石材",
    "Flexible Stone": "柔性石材",
    "Ceramic/Porcelain Tile": "陶瓷/瓷砖",
    "Ceramic & Porcelain Tile": "陶瓷与瓷砖",

    # --- Nav / footer / UI labels ---
    "Home": "首页",
    "Products": "产品",
    "Downloads": "下载",
    "Projects": "项目",
    "Insights": "资讯",
    "Contact": "联系我们",
    "Resources": "资源",
    "FAQ": "常见问题",
    "Colour Library": "色彩库",
    "Compare": "对比",
    "Certifications": "认证",
    "Get a Quote": "获取报价",
    "Request Samples": "索取样品",
    "Email Us": "邮箱联系",
    "WhatsApp Us": "WhatsApp 联系",
    "WhatsApp": "WhatsApp",
    "Request samples & a quote": "索取样品与报价",
    "Request a Quote": "获取报价",

    # --- Footer / brand boilerplate ---
    "Building for a Sustainable Future": "为可持续的未来而建",
    "Foshan sourcing base · Singapore headquarters.": "佛山采购基地 · 新加坡总部。",
    "Quality from China. Trust from Singapore.": "源自中国的品质。来自新加坡的信任。",
    "© 2026 YENYONG. · Foshan YenYong International Building Materials Trading Co., Ltd. · OVERARCHING PTE. LTD. · Singapore": "© 2026 YENYONG. · 佛山扬永国际建材贸易有限公司 · OVERARCHING PTE. LTD. · 新加坡",
    "www.yenyong.com": "www.yenyong.com",
}
